---
- name: Check if git prompt exists
  stat: path=/home/vagrant/.git-prompt.sh
  register: git_prompt

- name: Change prompt
  template:
    src: ../templates/bashrc.j2
    dest: /home/vagrant/.bashrc
  when: git_prompt.stat.exists == False

- name: Download git prompt
  get_url: url=https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh dest=/home/vagrant/.git-prompt.sh force=yes
  when: git_prompt.stat.exists == False

- file: path=/home/vagrant/.git-prompt.sh owner=vagrant group=vagrant

- name: Set timezone
  replace: >
    dest="/etc/timezone"
    regexp="^(?!Europe/Copenhagen)[^\n]+"
    replace="Europe/Copenhagen"

- name: Check if mole completion is enabled
  command: grep "_mole_completion" ~/.profile
  register: mole_result
  sudo: no
  ignore_errors: True

- name: Enable mole completion
  template:
    src: ../templates/profile.j2
    dest: ~/.profile
  when: "mole_result|failed"
  sudo: no
